### ISSUE TITLE
Conflict with metalsmith-permalinks?

### ISSUE THREAD

**Issue by gpaumier** [ahmadnassri/metalsmith-paths#2]
Hi there,

Thank you for this plugin. I've tried to use it but it seems to conflict with [metalsmith-permalinks](https://github.com/segmentio/metalsmith-permalinks).

Unless I'm missing something, both seem to use the `path` property, so the path gets overwritten when the paths plugin runs before the permalinks plugin.

Can you confirm this issue? If so, would it make sense to rename the property to avoid the conflict? I'm using this method as a workaround on my local version, but it would be nice to do it in the repository.

**Comment by ahmadnassri** [comment]
you are correct, and though its typical to get conflicts like this ... it's usually rare.

to that end, I made the property customizable, see updated README in `v2.1.0`

**Comment by gpaumier** [comment]
@ahmadnassri Thank you so much! It works perfectly.
