### ISSUE TITLE
2.1.2 breaking change: path.href now includes filename

### ISSUE THREAD

**Issue by brycekahle** [ahmadnassri/metalsmith-paths#31]
This completely broke our metalsmith build. Luckily I had a link checker that caught it.

See the test change here:
https://github.com/ahmadnassri/metalsmith-paths/commit/f5eb149e30f9eed3e931c07d4c170a77281f6359#diff-910eb6f57886ca16c136101fb1699231R24

**Comment by mbellet** [comment]
I had the same problem, it's possible to put a variable to disable filename in href or/and put the regex support in "directoryIndex" variable?

**Comment by ahmadnassri** [comment]
hey guys, sorry about this, I'm currently traveling, happy to accept PR with fix.

**Comment by ahmadnassri** [comment]
this has been addressed in the latest release by introducing `dhref` to point to the directory.
