### ISSUE TITLE
On windows, backslash instead of forwardslash in directory string

### ISSUE THREAD

**Issue by itenisz** [ahmadnassri/metalsmith-paths#70]
Hello!

On windows, there is a problem with directory string because contains backslash instead of forward slash.
Error example:
paths.dir         maindir\subdir
paths.href       /maindir\subdir/index.html 
paths.dhref    /maindir\subdir/ 

It should be:
paths.dir         maindir/subdir
paths.href       /maindir/subdir/index.html 
paths.dhref    /maindir/subdir/

**Comment by SmashManiac** [comment]
Reproduced.

**Comment by ahmadnassri** [comment]
this is fixed in v4.0.0
